// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: internal/grpc/proto/roller.proto

package roller

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RollerClient is the client API for Roller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RollerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Roll(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type rollerClient struct {
	cc grpc.ClientConnInterface
}

func NewRollerClient(cc grpc.ClientConnInterface) RollerClient {
	return &rollerClient{cc}
}

func (c *rollerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/Roller/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollerClient) Roll(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/Roller/Roll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RollerServer is the server API for Roller service.
// All implementations must embed UnimplementedRollerServer
// for forward compatibility
type RollerServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Roll(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedRollerServer()
}

// UnimplementedRollerServer must be embedded to have forward compatible implementations.
type UnimplementedRollerServer struct {
}

func (UnimplementedRollerServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRollerServer) Roll(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Roll not implemented")
}
func (UnimplementedRollerServer) mustEmbedUnimplementedRollerServer() {}

// UnsafeRollerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RollerServer will
// result in compilation errors.
type UnsafeRollerServer interface {
	mustEmbedUnimplementedRollerServer()
}

func RegisterRollerServer(s grpc.ServiceRegistrar, srv RollerServer) {
	s.RegisterService(&Roller_ServiceDesc, srv)
}

func _Roller_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Roller/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roller_Roll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollerServer).Roll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Roller/Roll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollerServer).Roll(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Roller_ServiceDesc is the grpc.ServiceDesc for Roller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Roller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Roller",
	HandlerType: (*RollerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Roller_Ping_Handler,
		},
		{
			MethodName: "Roll",
			Handler:    _Roller_Roll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/proto/roller.proto",
}
